Repository codesquad-members-2023/fe-news, pull requests merged in 2023-04, with the labels that each got.

#11 [jayden] w01/mid(final)
  .eslintrc
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  postcss.config.js
  public/index.html
  readme.md
  src/app.ts
  src/components/footer/FooterComponent.ts
  src/components/footer/FooterModel.ts
  src/components/footer/FooterView.ts
  src/components/header/HeaderComponent.ts
  src/components/header/HeaderModel.ts
  src/components/header/HeaderView.ts
  src/components/main/MainComponent.ts
  src/components/main/MainModel.ts
  src/components/main/MainView.ts
  src/components/main/Main__right/MainRightComponent.ts
  src/components/main/Main__right/MainRightModel.ts
  src/components/main/Main__right/MainRightView.ts
  src/styles/global.css
  src/utils/interfaces.ts
  src/utils/types.ts
  tailwind.config.js
  tsconfig.json
Labels: midpoint, final

#6 [Lily] 1주차 학습 계획 작성
  .eslintrc.yml
  .gitignore
  .prettierignore
  asset/logo.svg
  db.json
  index.html
  package.json
  readme.md
  src/app.js
  src/pages/header/header.js
  src/pages/header/headerUI.js
  src/pages/mainSection/mainGridCellUI.js
  src/pages/mainSection/mainGridView.js
  src/pages/mainSection/mainView.js
  src/script/utils.js
  src/style/common.css
  src/style/header.css
  src/style/init.css
  src/style/main.css
  src/style/mainGridView.css
  src/style/variables.css
Labels: final

#10 [시저] Week1/Final
  .gitignore
  assets/icons/chevron-right.svg
  assets/icons/close.svg
  assets/icons/grid-view.svg
  assets/icons/leftButton.svg
  assets/icons/list-view.png
  assets/icons/list-view.svg
  assets/icons/newspaper.svg
  assets/icons/plus.svg
  assets/icons/rightButton.svg
  crawl.js
  db.json
  index.html
  package-lock.json
  package.json
  readme.md
  src/App.js
  src/components/Bar.js
  src/components/Cell.js
  src/components/Label.js
  src/components/LatestNews.js
  src/components/OptionListContainer.js
  src/components/Tab.js
  src/components/Viewer.js
  src/core/Component.js
  src/index.js
  src/storage/storageUtils.js
  style.css
Labels: final

#7 [nanii] 1주차 NEWS STAND 학습 계획서
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  public/index.html
  readme.md
  src/assets/icons/GridBtn.svg
  src/assets/icons/LeftButton.svg
  src/assets/icons/ListBtn.svg
  src/assets/icons/Newsstand.svg
  src/assets/icons/RightButton.svg
  src/css/style.css
  src/js/app.js
  src/js/components/header/header.js
  src/js/components/main/buttons/sortButton.js
  src/js/components/section/rollingBar.js
  src/js/core/constants.js
  src/js/utils/systemTime.js
  src/js/utils/util.js
  src/sass/abstracts/_functions.scss
  src/sass/abstracts/_mixins.scss
  src/sass/abstracts/_variables.scss
  src/sass/base/_base.scss
  src/sass/base/_normalize.scss
  src/sass/base/_typography.scss
  src/sass/layout/_grid.scss
  src/sass/layout/_header.scss
  src/sass/layout/_section.scss
  src/sass/layout/_sortButtons.scss
  src/sass/style.scss
Labels: final

#3 [Poco] 1주차 학습계획
  app.js
  db.json
  index.html
  package-lock.json
  package.json
  readme.md
  sass/abstracts/_mixins.scss
  sass/abstracts/_variables.scss
  sass/base/_base.scss
  sass/base/_typography.scss
  sass/layout/_header.scss
  sass/layout/_headline.scss
  sass/layout/_section.scss
  sass/layout/_sectionGrid.scss
  sass/main.scss
  src/asset/headerIcon.svg
  src/asset/newsSectionGridViewButton.svg
  src/asset/newsSectionLeftButton.svg
  src/asset/newsSectionListViewButton.svg
  src/asset/newsSectionRightButton.svg
  src/js/const/const.js
  src/js/crawl/headlineCrawl.js
  src/js/dataFetcher/dataFetcher.js
  src/js/domMaker/headerMaker.js
  src/js/domMaker/headlineMaker.js
  src/js/newsStandView.js
  style.css
Labels: final

#1 [hoonding] 1주차 학습계획 및 체크리스트 작성
  .gitignore
  .prettierrc
  asset/grid-icon.svg
  asset/list-icon.svg
  asset/logo.svg
  crawl/mediaCrwal.js
  css/style.css
  db.json
  index.html
  js/actions/ActionTypes.js
  js/actions/Actions.js
  js/api/Request.js
  js/components/App.js
  js/components/AutoRolling/autoRolling.js
  js/components/AutoRolling/autoRollingAnimaiton.js
  js/components/Header.js
  js/components/main/mainHeader.js
  js/constants/api.js
  js/dispatcher/AppDispatcher.js
  js/index.js
  js/store/autoRollingReducer.js
  js/store/dataReducer.js
  js/store/store.js
  js/utils/createStore.js
  js/utils/dom.js
  package-lock.json
  package.json
  readme.md
  sass/abstracts/_variables.scss
  sass/base/_base.scss
  sass/base/_typography.scss
  sass/layout/_auto-rolling.scss
  sass/layout/_header.scss
  sass/main.scss
Labels: final

#9 [den] Week1 학습계획
  .eslintrc
  .gitignore
  .vscode/settings.json
  db.json
  docs/planner.md
  index.html
  package-lock.json
  package.json
  readme.md
  src/api.js
  src/app.js
  src/common.css
  src/components/Header.js
  src/components/TrendNews.js
  src/components/ViewContainer/GridItem.js
  src/components/ViewContainer/GridView.js
  src/core/Component.js
  src/crawl.js
  src/images/grid_btn.svg
  src/images/lg_left_dir_btn.svg
  src/images/lg_right_dir_btn.svg
  src/images/list_btn.svg
  src/images/newsstand_logo.svg
  src/images/sm_right_dir_btn.svg
  src/images/subscribe_btn.svg
  src/index.js
Labels: documentation, final

#2 [워터] W01 학습계획
  .eslintrc.js
  .gitignore
  assets/newsPaper.svg
  index.html
  json-server/db.json
  package.json
  readme.md
  script/main.js
  script/newsHeader/headerDate.js
  script/newsHeader/hederLogo.js
  script/newsHeader/newsHeader.js
  script/store/logoStore.js
  style/common/common.css
  style/common/reset.css
  style/css/font.css
  style/css/newsHeader.css
  style/css/variable.css
  style/scss/dist/variable.css
  style/scss/font.scss
  style/scss/newsHeader.scss
  style/scss/variable.scss
Labels: documentation

#4 [sarang_daddy] News_Stand 1주차
  css/common/button.css
  css/common/fonts.css
  css/common/logo.css
  css/common/root.css
  css/components/news-journal-carousel.css
  css/reset.css
  css/screens/news-head-line.css
  css/screens/news-header.css
  css/screens/news-journal.css
  css/screens/news-stand.css
  css/styles.css
  index.html
  readme.md
  src/api/getHeadLineData.js
  src/api/getJournalListData.js
  src/assets/icons/LeftButton.svg
  src/assets/icons/NewsLogo.svg
  src/assets/icons/RightButton.svg
  src/assets/icons/chevron-right.svg
  src/assets/icons/close.svg
  src/assets/icons/gray-label.svg
  src/assets/icons/grid-view-on.svg
  src/assets/icons/grid-view.svg
  src/assets/icons/list-view-on.svg
  src/assets/icons/list-view.svg
  src/assets/icons/newspaper.svg
  src/assets/icons/plus.svg
  src/assets/icons/white-label.svg
  src/assets/icons/white-symbol.svg
  src/components/headLine/headLineClass.js
  src/components/headLine/headLineView.js
  src/components/header/headerView.js
  src/components/header/todayNotice.js
  src/components/journalList/journalClass.js
  src/components/journalList/journalListView.js
  src/getData/headLineData.js
  src/getData/journalData.js
  src/json-server/db.json
  src/main.js
Labels: documentation

#5 [daon] 1주차 학습계획 작성
  .prettierrc.json
  package.json
  public/index.html
  readme.md
  src/app.js
  src/assets/images/arrow_right.svg
  src/assets/images/grid.svg
  src/assets/images/list.svg
  src/assets/images/mutiply.svg
  src/assets/images/newsstand_logo.svg
  src/assets/images/plus.svg
  src/pages/autoRolling.js
  src/pages/header.js
  src/styles/scss/autoRolling.scss
  src/styles/scss/header.scss
  src/styles/scss/main.scss
  src/styles/scss/reset.scss
  src/styles/scss/variables.scss
  src/styles/style.css
  src/styles/style.css.map
Labels: documentation

#8 [아켄] 1주차 학습 계획 작성
  .eslintrc.json
  .prettierrc
  index.html
  package.json
  readme.md
  src/css/style.css
  src/css/style.css.map
  src/images/grid_blue.svg
  src/images/list_gray.svg
  src/images/logo.svg
  src/js/app.js
  src/js/components/header.js
  src/js/components/mainContent/mainContent.js
  src/js/components/mainContent/mainContentHeader.js
  src/js/index.js
  src/js/utils/dom.js
  src/sass/abstracts/_mixins.scss
  src/sass/abstracts/_variables.scss
  src/sass/base/_reset.scss
  src/sass/base/_typography.scss
  src/sass/components/header.scss
  src/sass/layout/_app.scss
  src/sass/layout/_header.scss
  src/sass/layout/_main-content.scss
  src/sass/style.scss
Labels: documentation, enhancement

#20 [hoonding] 2주차 학습계획 및 체크리스트 작성.
  asset/gridIcon.svg
  asset/leftButton.svg
  asset/listIcon.svg
  asset/rightButton.svg
  asset/subscribeButton.svg
  asset/unsubscribeButton.svg
  css/style.css
  js/actions/ActionTypes.js
  js/actions/Actions.js
  js/api/Request.js
  js/components/App.js
  js/components/AutoRolling/autoRolling.js
  js/components/AutoRolling/autoRollingAnimaiton.js
  js/components/AutoRolling/index.html
  js/components/Header.js
  js/components/main/MainAllGrid/mainAllGrid.js
  js/components/main/MainAllGrid/mainAllGridEventHandlers.js
  js/components/main/MainAllLIst/mainAllList.js
  js/components/main/MainAllLIst/mainAllListEventHandlers.js
  js/components/main/MainCommon/mainButtonEventHandlers.js
  js/components/main/MainCommon/mainCommon.js
  js/components/main/mainHeader.html
  js/components/main/mainHeader.js
  js/store/dataReducer.js
  js/store/displayReducer.js
  js/store/store.js
  readme.md
  sass/base/_base.scss
  sass/layout/_auto-rolling.scss
  sass/layout/_header.scss
  sass/layout/_main-common.scss
  sass/layout/_main-grid.scss
  sass/layout/_main-list.scss
  sass/main.scss
Labels: midpoint

#22 [아켄] 2주차 학습 정리
  readme.md
  src/css/style.css
  src/css/style.css.map
  src/images/grid_gray.svg
  src/images/list_blue.svg
  src/js/app.js
  src/js/components/header.js
  src/js/components/header/index.js
  src/js/components/mainContent/index.js
  src/js/components/mainContent/mainContent.js
  src/js/components/mainContent/mainContentHeader.js
  src/js/components/nav/headLineWrapper.js
  src/js/components/nav/index.js
  src/js/components/nav/navBar.js
  src/js/index.js
  src/js/utils/getData.js
  src/mock/gridData.json
  src/mock/navBarData.json
  src/sass/base/_typography.scss
  src/sass/components/_nav.scss
  src/sass/layout/_nav.scss
  src/sass/style.scss
Labels: midpoint

#14 [Lily] 2w - main view (grid type)
  asset/LeftButton.svg
  asset/RightButton.svg
  asset/SubscribeButton.svg
  asset/UnsubscribeButton.svg
  asset/gridView.svg
  asset/listView.svg
  index.html
  package.json
  src/app.js
  src/pages/header/headerHandler.js
  src/pages/header/headerView.js
  src/pages/mainSection/directionBtn.js
  src/pages/mainSection/mainGridView.js
  src/pages/mainSection/mainHandler.js
  src/pages/mainSection/mainView.js
  src/pages/mainSection/pressGridView.js
  src/pages/mainSection/pressListView.js
  src/pages/mainSection/pressesGridView.js
  src/pages/mainSection/pressesListView.js
  src/pages/mainSection/viewSelectBtn.js
  src/script/utils.js
  src/style/header.css
  src/style/main.css
  src/style/mainGridView.css
  src/style/reset.css
Labels: midpoint

#15 [sarang_daddy] 2주차
  css/common/button.css
  css/common/display.css
  css/common/fonts.css
  css/common/logo.css
  css/components/news-journal-carousel.css
  css/news-stand/components/news-head-line/news-head-line.css
  css/news-stand/components/news-header.css/news-header.css
  css/news-stand/components/news-journal/carousel.css
  css/news-stand/components/news-journal/news-journal.css
  css/news-stand/news-stand.css
  css/screens/news-header.css
  css/styles.css
  db.json
  package.json
  src/Crawling/headLineData.js
  src/Crawling/journalData.js
  src/api/getData.js
  src/api/getHeadLineData.js
  src/api/getJournalListData.js
  src/components/headLine/headLineClass.js
  src/components/headLine/headLineView.js
  src/components/header/headerView.js
  src/components/journalList/journalCarousel.js
  src/components/journalList/journalClass.js
  src/components/journalList/journalListView.js
  src/components/journalList/subJournalView.js
  src/getData/headLineData.js
  src/getData/journalData.js
  src/main.js
  src/testFolder/journalActions.js
  src/testFolder/journalDispatcher.js
  src/testFolder/journalStore.js
Labels: midpoint

#16 [Poco] 뉴스스탠드 2주차 학습계획
  app.js
  readme.md
  sass/layout/_header.scss
  src/js/const/const.js
  src/js/constant/api.js
  src/js/constant/dom.js
  src/js/crawler/headlineCrawler.js
  src/js/domMaker/headerMaker.js
  src/js/domMaker/headlineMaker.js
  src/js/newsStandView.js
  src/js/utils/dataFetcher.js
  src/js/view/NSHeaderView.js
  src/js/view/NSHeadlineView.js
  style.css
Labels: midpoint

#19 [nanii] 2주차 midpoint
  db.json
  package.json
  public/index.html
  src/css/style.css
  src/js/app.js
  src/js/components/header.js
  src/js/components/header/header.js
  src/js/components/main/buttons/sortButton.js
  src/js/components/main/viewContainer/grid/grid.js
  src/js/components/main/viewContainer/mainView.js
  src/js/components/rollingBar.js
  src/js/components/section/rollingBar.js
  src/js/core/Store.js
  src/js/core/constants.js
  src/js/stores/rollingStore.js
  src/js/stores/viewStore.js
  src/js/utils/fetch.js
  src/js/utils/randomData.js
  src/sass/base/_base.scss
  src/sass/base/_normalize.scss
  src/sass/layout/_grid.scss
Labels: midpoint

#21 [워터] w2 학습 계획 및 설계
  assets/leftButton.svg
  assets/rightButton.svg
  assets/rollingLogo.svg
  assets/viewDetail.svg
  assets/viewLogo.svg
  index.html
  json-server/db.json
  package.json
  readme.md
  script/controller/controller.js
  script/controller/fetchManager.js
  script/main.js
  script/newsHeader/headerDate.js
  script/newsHeader/hederLogo.js
  script/newsHeader/newsHeader.js
  script/store/logoStore.js
  script/store/makeData.js
  script/view/newsCompany.js
  script/view/newsHeader.js
  script/view/rollingBar.js
  style/common/common.css
  style/common/reset.css
  style/css/style.css
  style/css/style.css.map
  style/css/variable.css
  style/scss/_font.scss
  style/scss/_newsCompany.scss
  style/scss/_newsHeader.scss
  style/scss/_newsRollingBar.scss
  style/scss/_reset.scss
  style/scss/_variable.scss
  style/scss/dist/variable.css
  style/scss/font.scss
  style/scss/newsHeader.scss
  style/scss/style.scss
Labels: midpoint

#26 [jayden] w02/final
  package.json
  readme.md
  src/components/footer/FooterComponent.ts
  src/components/footer/FooterModel.ts
  src/components/footer/FooterView.ts
  src/components/header/HeaderComponent.ts
  src/components/header/HeaderModel.ts
  src/components/header/HeaderView.ts
  src/components/main/MainComponent.ts
  src/components/main/MainModel.ts
  src/components/main/MainView.ts
  src/components/main/main__left/MainLeftComponent.ts
  src/components/main/main__left/MainLeftModel.ts
  src/components/main/main__left/MainLeftView.ts
  src/components/main/main__left/ns__container/NsContainerComponent.ts
  src/components/main/main__left/ns__container/NsContainerModel.ts
  src/components/main/main__left/ns__container/NsContainerView.ts
  src/components/main/main__left/ns__container/ns__category-container/NsCategoryContainerObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__category-container/NsCategoryContainerObsevableModel.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarModel.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarView.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__left/NavbarLeftComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__left/NavbarLeftModel.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__left/NavbarLeftView.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightModel.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightView.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerComponent.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerModel.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerView.ts
  src/components/main/main__left/ns__header/NsHeaderComponent.ts
  src/components/main/main__left/ns__header/NsHeaderModel.ts
  src/components/main/main__left/ns__header/NsHeaderView.ts
  src/components/main/main__left/ns__header/ns__date/NsDateComponent.ts
  src/components/main/main__left/ns__header/ns__date/NsDateModel.ts
  src/components/main/main__left/ns__header/ns__date/NsDateView.ts
  src/components/main/main__left/ns__header/ns__title/NsTitleComponent.ts
  src/components/main/main__left/ns__header/ns__title/NsTitleModel.ts
  src/components/main/main__left/ns__header/ns__title/NsTitleView.ts
  src/components/main/main__left/ns__issue-container/NsIssueContainerComponent.ts
  src/components/main/main__left/ns__issue-container/NsIssueContainerModel.ts
  src/components/main/main__left/ns__issue-container/NsIssueContainerView.ts
  src/components/main/main__left/ns__issue-container/ns__issue/NsIssueComponent.ts
  src/components/main/main__left/ns__issue-container/ns__issue/NsIssueModel.ts
  src/components/main/main__left/ns__issue-container/ns__issue/NsIssueView.ts
  src/components/main/main__right/MainRightComponent.ts
  src/components/main/main__right/MainRightModel.ts
  src/components/main/main__right/MainRightView.ts
  src/constants/constants.ts
  src/index.ts
  src/types/abstracts.ts
  src/types/interfaces.ts
  src/types/types.ts
  src/utils/dom.ts
  tailwind.config.js
  tsconfig.json
Labels: final

#27 [hoonding] 2주차 - final
  asset/subscribeButton.svg
  asset/unsubscribeButton.svg
  css/style.css
  index.html
  js/App.js
  js/actions/ActionTypes.js
  js/actions/Actions.js
  js/api/Request.js
  js/components/main/MainAllGrid/mainAllGrid.js
  js/components/main/MainAllLIst/mainAllList.html
  js/components/main/MainAllLIst/mainAllList.js
  js/components/main/MainCommon/mainButtonEventHandlers.js
  js/components/main/MainCommon/mainCommon.js
  js/components/main/mainHeader.html
  js/index.js
  js/store/displayReducer.js
  js/store/store.js
  js/utils/createStore.js
  sass/abstracts/_functions.scss
  sass/layout/_auto-rolling.scss
  sass/layout/_main-common.scss
  sass/layout/_main-list.scss
Labels: final

#28 [snoop] W2 final
  server/app.ts
  server/schemas/index.ts
  src/apis/user.ts
  src/components/News/PressList/PressListContents/GridView/GridView.ts
  src/components/News/PressList/PressListContents/GridView/GridViewItem/GridViewItem.ts
  src/components/News/PressList/PressListContents/ListView/ListView.ts
  src/components/News/PressList/PressListContents/ListView/ListViewItem/ListViewItem.ts
  src/components/News/PressList/PressListContents/PressListContents.ts
  src/store/press/pressType.ts
Labels: final

#29 [Poco] 뉴스스탠드 2주차 final
  .gitignore
  app.js
  db.json
  index.html
  sass/layout/_section.scss
  sass/layout/_sectionGrid.scss
  src/js/constant/api.js
  src/js/constant/dom.js
  src/js/crawler/NSSectionCrawler.js
  src/js/models/NSSectionButtonModel.js
  src/js/models/NSSectionHeaderModel.js
  src/js/models/gridAllModel.js
  src/js/models/observer.js
  src/js/utils/dataFetcher.js
  src/js/view/NSHeadlineView.js
  src/js/view/NSSectionButtonView.js
  src/js/view/NSSectionHeaderView.js
  src/js/view/gridAllView.js
  style.css
Labels: final

#30 [Lily] main view (list type)
  .eslintignore
  asset/SubscribeButton.svg
  asset/gridViewButton.svg
  asset/listViewButton.svg
  index.html
  src/app.js
  src/pages/header/headerView.js
  src/pages/mainSection/UnsubscribeModal.js
  src/pages/mainSection/directionBtn.js
  src/pages/mainSection/mainHandler.js
  src/pages/mainSection/mainView.js
  src/pages/mainSection/pressGridView.js
  src/pages/mainSection/pressListView.js
  src/pages/mainSection/pressesGridView.js
  src/pages/mainSection/pressesListView.js
  src/pages/mainSection/viewSelectBtn.js
  src/pages/mainSection/viewSelectionBtn.js
  src/script/contents.js
  src/style/header.css
  src/style/main.css
  src/style/mainGridView.css
  src/style/mainSectionView.css
  src/style/reset.css
Labels: final

#31 [nanii] 2주차 final
  db.json
  readme.md
  src/css/style.css
  src/js/app.js
  src/js/components/main/buttons/sortButton.js
  src/js/components/main/grid.js
  src/js/components/main/main.js
  src/js/components/main/sortButton.js
  src/js/components/main/viewContainer/grid/grid.js
  src/js/components/main/viewContainer/mainView.js
  src/js/components/rollingBar.js
  src/js/core/Store.js
  src/js/core/constants.js
  src/js/stores/rollingStore.js
  src/js/stores/subscribeStore.js
  src/js/stores/viewStore.js
  src/sass/abstracts/_variables.scss
  src/sass/base/_base.scss
  src/sass/layout/_grid.scss
  src/sass/layout/_sortButtons.scss
  src/sass/style.scss
Labels: final

#33 [den] w02/final
  db.json
  index.html
  src/api/api.js
  src/app.js
  src/components/Header/Header.js
  src/components/MainView/GridView/GridItem.js
  src/components/MainView/GridView/GridView.js
  src/components/MainView/ListView/ListView.js
  src/components/MainView/ListView/ListViewHeader.js
  src/components/MainView/ListView/ListViewMain.js
  src/components/MainView/ListView/ListViewSubscribeBtn.js
  src/components/MainView/MainView.js
  src/components/MainView/NoticeView/NoticeView.js
  src/style/common.css
  src/style/index.css
  src/style/reset.css
  src/utils/utils.js
Labels: final

#34 [아켄] 2주차 final
  package.json
  readme.md
  src/css/style.css
  src/css/style.css.map
  src/js/app.js
  src/js/components/mainContent/index.js
  src/js/components/mainContent/mainContentContainer.js
  src/js/components/mainContent/mainContentGrid.js
  src/js/components/mainContent/mainContentHeader.js
  src/js/components/mainContent/pressGrid.js
  src/js/components/mainContent/pressGridItem.js
  src/js/components/mainContent/pressTab.js
  src/js/components/mainContent/showTab.js
  src/js/components/nav/index.js
  src/js/core/store.js
  src/js/index.js
  src/js/reducer/tabReducer.js
  src/js/store/tabStore.js
  src/js/utils/getData.js
  src/mock/db.json
  src/mock/gridData.json
  src/mock/navBarData.json
  src/sass/abstracts/_variables.scss
  src/sass/base/_typography.scss
  src/sass/components/_app.scss
  src/sass/components/_main-content.scss
  src/sass/layout/_app.scss
  src/sass/layout/_main-content.scss
  src/sass/style.scss
Labels: final

#35 [sarang_daddy] News-stand 2주차 Final
  css/news-stand/components/news-head-line/news-head-line.css
  css/news-stand/components/news-journal/news-journal.css
  src/components/headLine/headLine.js
  src/components/headLine/headLineView.js
  src/components/journalList/journal.js
  src/components/journalList/journalHeader.js
  src/components/journalList/journalListView.js
  src/components/journalList/journalTrack.js
  src/components/journalList/subJournalView.js
  src/main.js
  src/store/journalHeaderStore.js
  src/testFolder/journalStore.js
Labels: final

#36 [워터] w3 final
  index.html
  json-server/db.json
  readme.md
  script/ crawling/store.js
  script/app.js
  script/constants/api.js
  script/controller/controller.js
  script/controller/fetchManager.js
  script/view/newsCompany.js
  script/view/newsRollingBar.js
  style/css/style.css
  style/css/style.css.map
  style/scss/_newsCompany.scss
Labels: final

#38 [시저] Week2/Final
  index.html
  src/App.js
  src/components/contents/Contents.js
  src/components/contents/grid/GridView.js
  src/components/contents/grid/Logo.js
  src/components/contents/list/ListView.js
  src/components/contents/list/NewsContent.js
  src/components/contents/list/SubscriptionTab.js
  src/components/label/Label.js
  src/components/latestNews/LatestNews.js
  src/components/latestNews/LatestNewsBar.js
  src/core/Component.js
  src/core/observer.js
Labels: final

#32 [daon] final
  db.json
  index.html
  src/app.js
  src/js/api/fetchData.js
  src/js/app.js
  src/js/components/header/header.js
  src/js/components/headline/headline.js
  src/js/components/main/grid.js
  src/js/components/main/header.js
  src/js/components/main/main.js
  src/pages/autoRolling.js
  src/pages/header.js
  src/styles/scss/grid.scss
  src/styles/scss/header.scss
  src/styles/scss/headline.scss
  src/styles/scss/main.scss
  src/styles/scss/mainView/header.scss
Labels: final

#39 [jayden] w03/mid
  babel.config.js
  jest.config.ts
  package-lock.json
  package.json
  public/images/symbols/grid-view-off.svg
  public/images/symbols/grid-view-on.svg
  public/images/symbols/list-view-off.svg
  public/images/symbols/list-view-on.svg
  public/index.html
  readme.md
  src/components/main/main__left/ns__container/NsContainerComponent.ts
  src/components/main/main__left/ns__container/NsContainerView.ts
  src/components/main/main__left/ns__container/ns__category-container/NsCategoryContainerObservableModel.ts
  src/components/main/main__left/ns__container/ns__category-container/NsCategoryContainerObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__category-container/ns__article-container/NsArticleContainerObservableModel.ts
  src/components/main/main__left/ns__container/ns__category-container/ns__article-container/NsArticleContainerObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__category-container/ns__category-navbar/NsCategoryNavbarObservableModel.ts
  src/components/main/main__left/ns__container/ns__category-container/ns__category-navbar/NsCategoryNavbarObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightView.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerComponent.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerView.ts
  src/components/main/main__left/ns__header/ns__date/NsDateComponent.ts
  src/constants/constants.ts
  src/utils/date.ts
  tailwind.config.js
  tests/utils/customFetch.test.ts
  tests/utils/date.test.ts
  tests/utils/dom.test.ts
Labels: midpoint

#40 [Poco] 뉴스스탠드 3주차 mid
  app.js
  sass/layout/_sectionGrid.scss
  src/asset/newsSectionGridNoSubButton.svg
  src/asset/newsSectionGridSubButton.svg
  src/js/constant/dom.js
  src/js/crawler/NSSectionCrawler.js
  src/js/models/NSSectionButtonModel.js
  src/js/models/NSSectionCurStateModel.js
  src/js/models/NSSectionHeaderModel.js
  src/js/models/gridAllModel.js
  src/js/models/gridSubModel.js
  src/js/models/observer.js
  src/js/utils/objectUtils.js
  src/js/view/NSHeadlineView.js
  src/js/view/NSSectionButtonView.js
  src/js/view/NSSectionHeaderView.js
  src/js/view/gridAllView.js
  src/js/view/gridSubView.js
  style.css
Labels: midpoint

#41 [nanii] 4월 3주차 midpoint
  db.json
  readme.md
  src/assets/icons/nextCategory.svg
  src/assets/icons/subscribe.svg
  src/assets/icons/unsubscribe.svg
  src/css/style.css
  src/js/app.js
  src/js/components/main/grid.js
  src/js/components/main/list.js
  src/js/components/main/main.js
  src/js/components/main/sortButton.js
  src/js/core/constants.js
  src/js/stores/pressPageStore.js
  src/js/stores/subscribePageStore.js
  src/js/stores/subscribeStore.js
  src/js/stores/viewStore.js
  src/sass/layout/_grid.scss
  src/sass/layout/_list.scss
  src/sass/layout/_subscribeButtons.scss
Labels: midpoint

#42 [아켄] news stand 3주차 mid
  readme.md
  src/css/style.css
  src/css/style.css.map
  src/images/before_btn.svg
  src/images/next_btn.svg
  src/js/components/mainContent/mainContentContainer.js
  src/js/components/mainContent/mainContentGrid.js
  src/js/components/mainContent/pressGrid.js
  src/js/components/mainContent/pressGridItem.js
  src/js/components/mainContent/pressTab.js
  src/js/components/mainContent/showTab.js
  src/js/components/nav/navBar.js
  src/js/core/myStore.js
  src/js/index.js
  src/js/reducer/index.js
  src/js/reducer/tabReducer.js
  src/js/store/index.js
  src/js/store/tabStore.js
  src/js/utils/dom.js
  src/js/utils/getData.js
  src/js/utils/index.js
  src/sass/layout/_main-content.scss
Labels: midpoint

#43 [훈딩] 3주차 뉴스 스탠드
  asset/listUnsubscribeBtn.svg
  css/style.css
  js/App.js
  js/actions/ActionTypes.js
  js/actions/Actions.js
  js/components/main/MainAllGrid/mainAllGrid.js
  js/components/main/MainAllGrid/mainAllGridEventHandlers.js
  js/components/main/MainAllLIst/mainAllList.html
  js/components/main/MainAllLIst/mainAllList.js
  js/components/main/MainAllLIst/mainAllListEventHandlers.js
  js/components/main/MainCommon/mainButtonEventHandlers.js
  js/components/main/MainCommon/mainCommon.js
  js/components/main/MainMineList/mainMineList.js
  js/components/main/MainMineList/mainMineListEventHandler.js
  js/components/main/mainHeader.html
  js/components/main/mainMineGrid/mainMineGird.js
  js/components/main/progressBarAnimation.js
  js/store/autoRollingReducer.js
  js/store/displayReducer.js
  js/store/store.js
  sass/base/_base.scss
  sass/layout/_main-common.scss
  sass/layout/_main-grid.scss
  sass/layout/_main-list.scss
Labels: midpoint

#44 [sarang_daddy] News_stand 3주차
  css/news-stand/components/news-journal/journal-track.css
  css/news-stand/components/news-journal/news-journal.css
  css/styles.css
  db.json
  readme.md
  src/api/fetchData.js
  src/api/getData.js
  src/assets/icons/크롱.png
  src/components/headLine/headLineView.js
  src/components/journalList/journal.js
  src/components/journalList/journalHeader.js
  src/components/journalList/journalListView.js
  src/components/journalList/journalTrack.js
  src/store/journalDetailStore.js
  src/store/journalHeaderStore.js
  src/store/journalTrackStore.js
Labels: midpoint

#46 [den] Week3 학습계획 + midpoint
  docs/planner.md
  package-lock.json
  package.json
  src/api/api.js
  src/app.js
  src/components/MainView/Buttons/FilterBtns.js
  src/components/MainView/GridView/GridView.js
  src/components/MainView/ListView/ListView.js
  src/components/MainView/ListView/ListViewAnimaionManager.js
  src/components/MainView/ListView/ListViewHeader.js
  src/components/MainView/ListView/ListViewMain.js
  src/components/MainView/MainView.js
  src/style/common.css
  src/utils/utils.js
Labels: midpoint

#47 [daon] midpoint
  src/js/api/fetchData.js
  src/js/app.js
  src/js/components/header/header.js
  src/js/constants/constants.js
  src/js/utils/currentDate.js
  src/js/utils/dataFetcher.js
  src/js/utils/randomData.js
Labels: midpoint

#48 [시저] Week3/Mid
  db.json
  index.html
  src/App.js
  src/components/contents/Contents.js
  src/components/contents/grid/GridView.js
  src/components/contents/grid/Logo.js
  src/components/contents/list/AllTab.js
  src/components/contents/list/ListView.js
  src/components/contents/list/NewsContent.js
  src/components/contents/list/SubscriptionTab.js
  src/components/contents/menu/StyleMenu.js
  src/components/contents/menu/SubscriptionMenu.js
  src/components/latestNews/LatestNews.js
  src/components/latestNews/LatestNewsBar.js
  src/core/Component.js
  src/core/Store.js
  src/core/observer.js
  src/store/store.js
Labels: midpoint

#49 [워터] w4
  index.html
  script/app.js
  script/constants/dom.js
  script/controller/controller.js
  script/controller/subscribeController.js
  script/controller/viewController.js
  script/store/NewsStore.js
  script/utils/dom.js
  script/view/dom.js
  script/view/newsCompany.js
  script/view/newsCompany/newsCompany.js
  script/view/newsCompany/newsCompanyDetail.js
  script/view/newsCompany/newsCompanySubscribe.js
  script/view/newsHeader.js
  script/view/newsRollingBar.js
  style/css/style.css
  style/css/style.css.map
  style/scss/_newsCompany.scss
Labels: midpoint, final

#50 [Lily] 3w main section features
  src/pages/mainSection/directionBtn.js
  src/pages/mainSection/mainHandler.js
  src/pages/mainSection/mainView.js
  src/pages/mainSection/pressListView.js
  src/pages/mainSection/pressesGridView.js
  src/pages/mainSection/pressesListView.js
  src/pages/mainSection/subscribeSnackbar.js
  src/script/api.js
  src/script/contents.js
  src/style/mainSectionView.css
Labels: midpoint

#51 [훈딩] 3주차 뉴스 스탠드 Final 풀리퀘
  crawl/mediaCrwal.js
  db.json
  index.html
  js/actions/ActionCreator.js
  js/actions/ActionTypes.js
  js/actions/Actions.js
  js/components/AutoRolling/autoRolling.js
  js/components/AutoRolling/autoRollingAnimaiton.js
  js/components/AutoRolling/index.html
  js/components/main/MainAllGrid/mainAllGrid.js
  js/components/main/MainAllGrid/mainAllGridEventHandlers.js
  js/components/main/MainAllLIst/mainAllList.js
  js/components/main/MainAllLIst/mainAllListEventHandlers.js
  js/components/main/MainCommon/mainButtonEventHandlers.js
  js/components/main/MainCommon/mainCommon.js
  js/components/main/MainMineList/mainMineList.js
  js/components/main/MainMineList/mainMineListEventHandler.js
  js/components/main/progressBarAnimation.js
  js/store/dataReducer.js
  js/store/displayReducer.js
  js/store/store.js
  js/utils/createStore.js
Labels: final

#52 [아켄] news stand 3주차 final
  readme.md
  src/css/style.css
  src/css/style.css.map
  src/js/components/header/index.js
  src/js/components/mainContent/grid/pressGrid.js
  src/js/components/mainContent/grid/pressGridItem.js
  src/js/components/mainContent/index.js
  src/js/components/mainContent/mainContentContainer.js
  src/js/components/mainContent/mainContentGrid.js
  src/js/components/mainContent/mainContentHeader.js
  src/js/components/mainContent/mainContentList.js
  src/js/components/mainContent/pressGrid.js
  src/js/components/mainContent/tab/pressTab.js
  src/js/components/mainContent/tab/showTab.js
  src/js/components/nav/headLineWrapper.js
  src/js/components/nav/index.js
  src/js/components/nav/navBar.js
  src/js/constants/index.js
  src/js/index.js
  src/js/reducer/index.js
  src/js/store/index.js
  src/js/utils/index.js
  src/mock/db.json
  src/sass/abstracts/_mixins.scss
  src/sass/base/_typography.scss
  src/sass/components/_main-content.scss
  src/sass/layout/_main-content.scss
  src/sass/layout/_nav.scss
Labels: final

#53 [nanii] 4월 3주차 final
  .prettierrc.json
  db.json
  readme.md
  src/css/style.css
  src/js/app.js
  src/js/components/header.js
  src/js/components/main/grid.js
  src/js/components/main/list.js
  src/js/components/main/main.js
  src/js/components/main/newsGridView.js
  src/js/components/main/newsListView.js
  src/js/components/main/newsMainView.js
  src/js/components/main/sortButton.js
  src/js/components/main/subscribeBtn.js
  src/js/components/rollingBar.js
  src/js/core/constants.js
  src/js/stores/pressPageStore.js
  src/js/stores/subscribeListStore.js
  src/js/stores/subscribePageStore.js
  src/js/stores/subscribePressPageStore.js
  src/js/stores/viewTypeStore.js
  src/js/utils/util.js
  src/sass/layout/_list.scss
Labels: final

#54 [sarang_daddy] News_Stand 3주차 final
  css/news-stand/components/news-journal/journal-detail.css
  css/news-stand/components/news-journal/journal-track.css
  css/news-stand/components/news-journal/news-journal.css
  css/news-stand/news-stand.css
  css/styles.css
  db.json
  src/assets/icons/SubscribeButton.svg
  src/components/journalList/journal.js
  src/components/journalList/journalListView.js
  src/components/journalList/journalTrack.js
  src/store/journalDetailStore.js
  src/store/journalHeaderStore.js
Labels: final

#55 [jayden] w03/final
  .vscode/settings.json
  src/components/footer/FooterView.ts
  src/components/header/HeaderView.ts
  src/components/main/MainView.ts
  src/components/main/main__left/MainLeftView.ts
  src/components/main/main__left/ns__container/NsContainerView.ts
  src/components/main/main__left/ns__container/ns__category-container/NsCategoryContainerObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__category-container/ns__article-container/NsArticleContainerObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__category-container/ns__category-navbar/NsCategoryNavbarObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarView.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__left/NavbarLeftView.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightView.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerView.ts
  src/components/main/main__left/ns__header/NsHeaderView.ts
  src/components/main/main__left/ns__header/ns__date/NsDateView.ts
  src/components/main/main__left/ns__header/ns__title/NsTitleView.ts
  src/components/main/main__left/ns__issue-container/NsIssueContainerView.ts
  src/components/main/main__left/ns__issue-container/ns__issue/NsIssueView.ts
  src/components/main/main__right/MainRightView.ts
  src/types/abstracts.ts
Labels: final

#57 [Poco] 뉴스스탠드 w4 mid
  app.js
  db.json
  sass/abstracts/_mixins.scss
  sass/base/_base.scss
  sass/layout/_sectionEmpty.scss
  sass/layout/_sectionList.scss
  sass/main.scss
  src/asset/newsSectionListNoSubButton.svg
  src/asset/newsSectionListSubButton.svg
  src/js/models/NSSectionCurStateModel.js
  src/js/utils/objectUtils.js
  src/js/view/NSHeadlineView.js
  src/js/view/NSSectionButtonView.js
  src/js/view/NSSectionGridAllbuttonView.js
  src/js/view/NSSectionGridSubButtonView.js
  src/js/view/NSSectionHeaderView.js
  src/js/view/NSSectionListAllButtonVIew.js
  src/js/view/gridAllView.js
  src/js/view/gridSubView.js
  src/js/view/listAllView.js
  style.css
Labels: midpoint

#60 [snoop] W4 midpoint
  server/app.ts
  server/mock/rollingnews.json
  server/package.json
  server/pnpm-lock.yaml
  server/routes/controllers/index.ts
  server/routes/controllers/news.ts
  server/routes/controllers/user.ts
  server/routes/news.router.ts
  server/routes/user.router.ts
  server/schemas/index.schemas.ts
  server/schemas/news.schemas.ts
  server/schemas/user.schemas.ts
  src/App.ts
  src/apis/news.ts
  src/apis/rollingNews.ts
  src/apis/user.ts
  src/components/News/Headline/Headline.ts
  src/components/News/Headline/HeadlineItem/HeadlineItem.ts
  src/components/News/Headline/HeadlineItem/HeadlineItemStyle.ts
  src/components/News/PressList/PressListContents/GridViewContainer/GridView/GridView.ts
  src/components/News/PressList/PressListContents/GridViewContainer/GridView/GridViewItem/GridViewItem.ts
  src/components/News/PressList/PressListContents/GridViewContainer/GridViewContainer.ts
  src/components/News/PressList/PressListContents/ListView/ListView.ts
  src/components/News/PressList/PressListContents/ListView/ListViewItem/ListViewItem.ts
  src/components/News/PressList/PressListContents/ListView/ListViewTab/ListViewTab.ts
  src/components/News/PressList/PressListContents/ListView/ListViewTab/ListViewTabItem/ListViewTabItemStyle.ts
  src/components/News/PressList/PressListContents/PressListContents.ts
  src/components/News/PressList/PressListContents/PressListController/PressListController.ts
  src/components/News/PressList/PressListContents/PressListController/PressListControllerStyle.ts
  src/components/News/PressList/PressListHeader/PressListHeader.ts
  src/components/index.ts
  src/constant/index.ts
  src/services/news/press/press.ts
  src/services/news/press/pressType.ts
  src/services/news/section/section.ts
  src/services/news/section/sectionType.ts
  src/store/display/display.ts
  src/store/display/displayType.ts
  src/store/index.ts
  src/store/news/news.ts
  src/store/news/newsType.ts
  src/store/press/press.ts
  src/store/press/pressType.ts
  src/store/rollingNews/rollingNews.ts
  src/store/rollingNews/rollingNewsType.ts
  src/store/section/section.ts
  src/store/section/sectionType.ts
  src/store/user/user.ts
  src/store/user/userType.ts
  src/utils/animation.ts
  src/utils/dom.ts
  src/utils/redux.ts
Labels: midpoint

#56 [jayden] w04/mid
  db.json
  src/components/app.ts
  src/components/footer/FooterComponent.ts
  src/components/footer/FooterView.ts
  src/components/header/HeaderComponent.ts
  src/components/header/HeaderView.ts
  src/components/main/MainComponent.ts
  src/components/main/MainView.ts
  src/components/main/main__left/MainLeftComponent.ts
  src/components/main/main__left/MainLeftView.ts
  src/components/main/main__left/ns__container/NsContainerComponent.ts
  src/components/main/main__left/ns__container/NsContainerView.ts
  src/components/main/main__left/ns__container/ns__category-container/NsCategoryContainerObserverViewComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/NsNavbarView.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__left/NavbarLeftComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__left/NavbarLeftView.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightComponent.ts
  src/components/main/main__left/ns__container/ns__navbar/navbar__right/NavbarRightView.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerComponent.ts
  src/components/main/main__left/ns__container/ns__press-container/NsPressContainerView.ts
  src/components/main/main__left/ns__header/NsHeaderComponent.ts
  src/components/main/main__left/ns__header/NsHeaderView.ts
  src/components/main/main__left/ns__header/ns__date/NsDateComponent.ts
  src/components/main/main__left/ns__header/ns__date/NsDateView.ts
  src/components/main/main__left/ns__header/ns__title/NsTitleComponent.ts
  src/components/main/main__left/ns__header/ns__title/NsTitleView.ts
  src/components/main/main__left/ns__issue-container/NsIssueContainerComponent.ts
  src/components/main/main__left/ns__issue-container/NsIssueContainerView.ts
  src/components/main/main__left/ns__issue-container/ns__issue/NsIssueComponent.ts
  src/components/main/main__left/ns__issue-container/ns__issue/NsIssueView.ts
  src/components/main/main__right/MainRightComponent.ts
  src/components/main/main__right/MainRightView.ts
  src/constants/constants.ts
  src/types/abstracts.ts
  src/types/interfaces.ts
Labels: midpoint

#59 [사랑대디] 뉴스스탠드 4주차 PR
  css/news-stand/components/news-journal/journal-detail.css
  src/components/journalList/journal.js
  src/components/journalList/journalHeader.js
  src/components/journalList/journalListView.js
  src/components/journalList/journalTrack.js
  src/store/journalTrackStore.js
Labels: midpoint

#61 [훈딩] 4주차 뉴스스탠드 Midpoint
  css/style.css
  js/App.js
  js/actions/ActionCreator.js
  js/actions/ActionTypes.js
  js/components/main/MainAllGrid/mainAllGridEventHandlers.js
  js/components/main/MainAllLIst/mainAllListEventHandlers.js
  js/components/main/MainMineList/mainMineList.js
  js/components/main/MainMineList/mainMineListEventHandler.js
  js/components/main/progressBarAnimation.js
  js/store/displayReducer.js
  js/store/store.js
  sass/layout/_alert.scss
  sass/layout/_main-grid.scss
  sass/main.scss
Labels: midpoint

#62 [아켄] 뉴스 스탠드 4주차
  .eslintrc.json
  cypress.config.js
  cypress/e2e/allGrid.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package.json
  readme.md
  src/css/style.css
  src/css/style.css.map
  src/js/components/mainContent/mainContentContainer.js
  src/js/components/mainContent/mainContentList.js
  src/js/constants/index.js
  src/js/reducer/index.js
  src/js/store/index.js
  src/js/utils/index.js
  src/sass/base/_typography.scss
  src/sass/components/_main-content.scss
  src/sass/layout/_header.scss
  src/sass/layout/_main-content.scss
Labels: midpoint

#63 [den] Week4 midpoint
  .gitignore
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  src/app.js
  src/components/Header/Header.js
  src/components/MainView/Buttons/FilterBtns.js
  src/components/MainView/Buttons/ViewBtns.js
  src/components/MainView/GridView/GridView.js
  src/components/MainView/GridView/ItemView.js
  src/components/MainView/ListView/ListView.js
  src/components/MainView/ListView/ListViewAnimaionManager.js
  src/components/MainView/ListView/ListViewHeader.js
  src/components/MainView/ListView/ListViewMain.js
  src/components/MainView/ListView/ListViewSubscribeBtn.js
  src/components/MainView/MainView.js
  src/components/MainView/NoticeView/NoticeView.js
  src/components/TrendNews/TrendNews.js
  src/constants/index.js
  src/constants/ui.js
  src/core/Component.js
  src/index.js
  webpack.config.js
Labels: midpoint
